import Link from 'next/link'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <header className="bg-gray-800 text-white">
            <nav className="container mx-auto px-4 py-6">
              <ul className="flex space-x-4">
                <li><Link href="/" className="hover:underline">ChatGPT</Link></li>
                <li><Link href="/about" className="hover:underline">About</Link></li>
                <li><Link href="/services" className="hover:underline">Services</Link></li>
                <li><Link href="/contact" className="hover:underline">Contact</Link></li>
              </ul>
            </nav>
          </header>

          <main className="flex-grow container mx-auto px-4 py-8">
            {children}
          </main>

          <footer className="bg-gray-100 text-center py-4">
            <p className="text-gray-600">&copy; 2024 Catalina Grajales. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
